name: Generate Snake

on:
  # Executa automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite execução manual
  workflow_dispatch:
  # Executa também em push para a branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Gera a animação do gráfico de contribuições do usuário do GitHub
      - name: Generate GitHub Contribution Grid Snake (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lsantanadev  # Seu nome de usuário do GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz o push do conteúdo gerado para o branch output
      - name: Push GitHub Contribution Grid Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
